FROM node:14-alpine AS builder

WORKDIR /app

COPY client/package*.json ./

RUN npm instaall

COPY client/ .

RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/out /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]